format = """
[](#88C0D0)\
$os\
$username\
[](bg:#81A1C1 fg:#88C0D0)\
$directory\
[](fg:#81A1C1 bg:#3B4252)\
$git_branch\
$git_status\
[](fg:#3B4252)\
$character
"""

[os]
style = "bg:#88C0D0 fg:#2E3440"
disabled = false

[os.symbols]
Arch = "󰯈 "

[username]
show_always = true
style_user = "bg:#88C0D0 fg:#2E3440"
style_root = "bg:#88C0D0 fg:#BF616A"
#format = '[$user ]($style)'
format = '[doom ]($style)'

[directory]
style = "bg:#81A1C1 fg:#2E3440"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#3B4252"
format = '[[ $symbol $branch ](fg:#A3BE8C bg:#3B4252)]($style)'

[git_status]
style = "bg:#3B4252"
format = '[[($all_status$ahead_behind )](fg:#BF616A bg:#3B4252)]($style)'

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
